from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import tempfile
import tomllib
import uuid
from contextlib import suppress
from dataclasses import dataclass, replace
from datetime import datetime
from itertools import pairwise
from pathlib import Path
from typing import Literal, cast

from pi_task.doctor import manager_pi_check, systemd_environment_check

THINKING_LEVELS = ("off", "minimal", "low", "medium", "high", "xhigh", "max")
TRUST_POLICIES = ("inherit", "approve", "deny")
_TASK_ID = re.compile(r"^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$")
_DURATION = re.compile(r"^(\d+)(s|m|h)$")
_GENERATED = "# Generated by pi-task. Do not edit.\n"
_UNIT_NAME = re.compile(r"^pi-task-(?P<task_id>.+)\.(?P<kind>service|timer)$")
# systemd kills a hung wrapper after the task timeout plus this grace window.
RUNTIME_BACKSTOP_GRACE_SECONDS = 120
# Process stop budget pieces (shared by the wrapper and generated units).
PROCESS_TERM_GRACE_SECONDS = 5
PROCESS_KILL_WAIT_SECONDS = 5
PROCESS_DRAIN_SECONDS = 5
PROCESS_FINALIZE_SLACK_SECONDS = 15
# TimeoutStopSec must cover TERM → KILL → drain → finalize/session lookup.
TIMEOUT_STOP_SECONDS = (
    PROCESS_TERM_GRACE_SECONDS
    + PROCESS_KILL_WAIT_SECONDS
    + PROCESS_DRAIN_SECONDS
    + PROCESS_FINALIZE_SLACK_SECONDS
)
# Client wait for `systemctl stop` sits above TimeoutStopSec.
SYSTEMCTL_STOP_TIMEOUT_SECONDS = TIMEOUT_STOP_SECONDS + 15


class TaskError(Exception):
    pass


@dataclass(frozen=True)
class Task:
    task_id: str
    name: str | None
    working_directory: Path
    prompt_kind: Literal["inline", "file"]
    prompt: str
    schedule_kind: Literal["calendar", "interval"]
    schedule: str
    catch_up: bool
    model: str
    thinking: str
    timeout_seconds: int
    trust: str
    paused: bool
    result_reporting: bool

    @property
    def schedule_summary(self) -> str:
        if self.schedule_kind == "interval":
            return f"every {self.schedule}"
        return self.schedule


@dataclass(frozen=True)
class CalendarPreview:
    occurrences: tuple[str, ...]


@dataclass(frozen=True)
class SchedulingState:
    summary: str
    detail: str


@dataclass(frozen=True)
class SyncResult:
    tasks: int
    orphans_removed: int


def _config_home() -> Path:
    value = os.environ.get("XDG_CONFIG_HOME")
    return Path(value).expanduser() if value else Path.home() / ".config"


def _data_home() -> Path:
    value = os.environ.get("XDG_DATA_HOME")
    return Path(value).expanduser() if value else Path.home() / ".local" / "share"


def task_directory() -> Path:
    return _config_home() / "pi-task" / "tasks"


def unit_directory() -> Path:
    return _config_home() / "systemd" / "user"


def timer_stamp_path(task_id: str) -> Path:
    return _data_home() / "systemd" / "timers" / f"stamp-pi-task-{task_id}.timer"


def resolve_executable(name: str, override: str) -> str:
    """Resolve a hard dependency: env override first, then PATH."""
    configured = os.environ.get(override)
    if configured:
        candidate = Path(configured).expanduser()
        if candidate.is_file() and os.access(candidate, os.X_OK):
            return str(candidate.absolute())
        raise TaskError(f"{override} does not identify an executable file")
    executable = shutil.which(name)
    if executable is None:
        raise TaskError(f"{name} was not found on PATH")
    return executable


# Back-compat alias for internal call sites written against the private name.
_resolve_executable = resolve_executable


def _run(
    command: list[str],
    *,
    environment: dict[str, str] | None = None,
    timeout: float = 10,
) -> subprocess.CompletedProcess[str]:
    try:
        return subprocess.run(
            command,
            check=False,
            capture_output=True,
            text=True,
            timeout=timeout,
            env={**(environment if environment is not None else os.environ), "LC_ALL": "C"},
        )
    except (OSError, subprocess.TimeoutExpired) as error:
        raise TaskError(f"could not run {command[0]}: {error}") from error


def validate_task_id(task_id: str) -> None:
    if len(task_id) > 63 or not _TASK_ID.fullmatch(task_id):
        raise TaskError(
            "task ID must be a lowercase slug (letters, numbers, and single hyphens; "
            "maximum 63 characters)"
        )


def parse_duration(value: str, *, minimum_seconds: int = 1, what: str = "duration") -> int:
    match = _DURATION.fullmatch(value)
    if match is None:
        raise TaskError(f"{what} must be a positive duration such as 30m, 2h, or 45s")
    amount = int(match.group(1))
    multiplier = {"s": 1, "m": 60, "h": 3600}[match.group(2)]
    seconds = amount * multiplier
    if seconds < minimum_seconds:
        if minimum_seconds >= 60 and seconds < 60:
            raise TaskError(f"{what} must be at least one minute")
        if seconds == 0:
            raise TaskError(f"{what} must be greater than zero")
        raise TaskError(f"{what} must be at least {minimum_seconds} seconds")
    return seconds


def parse_timeout(value: str) -> int:
    return parse_duration(value, minimum_seconds=1, what="timeout")


def parse_interval(value: str) -> int:
    return parse_duration(value, minimum_seconds=60, what="interval")


def list_available_models() -> list[str]:
    """Return sorted ``provider/model`` values available to the systemd user manager.

    Uses the same Pi inventory scheduled runs will see. Raises :class:`TaskError`
    when the manager environment cannot be inspected, Pi cannot list models, or
    no models are authenticated.
    """
    systemd_status, manager_environment = systemd_environment_check()
    if manager_environment is None:
        raise TaskError(
            f"could not inspect models in the systemd user manager: {systemd_status.detail}"
        )
    pi_status, executable, manager_environment = manager_pi_check(manager_environment)
    if executable is None or manager_environment is None:
        raise TaskError(f"could not inspect models in the systemd user manager: {pi_status.detail}")
    result = _run([executable, "--list-models"], environment=manager_environment)
    if result.returncode != 0:
        detail = result.stderr.strip() or f"Pi exited with status {result.returncode}"
        raise TaskError(f"could not list models in the systemd user manager: {detail}")
    available = {
        f"{columns[0]}/{columns[1]}"
        for line in result.stdout.splitlines()[1:]
        if len(columns := line.split()) >= 2
    }
    if not available:
        raise TaskError(
            "no models are available to the systemd user manager; "
            "authenticate at least one provider with Pi (see `pi-task doctor`)"
        )
    return sorted(available)


def validate_model(model: str) -> None:
    if model.count("/") != 1 or any(character.isspace() for character in model):
        raise TaskError("model must use the explicit provider/model form")
    available = set(list_available_models())
    if model not in available:
        raise TaskError(f"model {model!r} is not available to the systemd user manager")


def _parse_occurrence(value: str) -> datetime | None:
    fields = value.strip().split(maxsplit=1)
    if len(fields) != 2:
        return None
    timestamp = fields[1]
    if timestamp.endswith(" UTC"):
        timestamp = timestamp[:-4] + "+00:00"
    try:
        return datetime.fromisoformat(timestamp)
    except ValueError:
        return None


def validate_calendar(expression: str) -> CalendarPreview:
    if not expression.strip() or "\n" in expression or "\r" in expression:
        raise TaskError("calendar schedule must be a single non-empty expression")
    executable = _resolve_executable("systemd-analyze", "PI_TASK_SYSTEMD_ANALYZE_EXECUTABLE")
    result = _run([executable, "calendar", "--iterations=3", expression])
    if result.returncode != 0:
        detail = result.stderr.strip() or f"systemd-analyze exited with status {result.returncode}"
        raise TaskError(f"invalid calendar schedule: {detail}")

    occurrence_lines: list[str] = []
    parsed: list[datetime] = []
    for line in result.stdout.splitlines():
        if "Next elapse:" in line or re.search(r"Iteration #\d+:", line):
            value = line.split(":", 1)[1].strip()
            occurrence_lines.append(value)
            occurrence = _parse_occurrence(value)
            if occurrence is not None:
                parsed.append(occurrence)
    if len(occurrence_lines) < 2:
        raise TaskError("calendar schedule does not have enough future occurrences")
    if len(parsed) >= 2 and any(
        (later - earlier).total_seconds() < 60 for earlier, later in pairwise(parsed)
    ):
        raise TaskError("calendar schedules must recur no faster than once per minute")
    return CalendarPreview(tuple(occurrence_lines))


def validate_interval(expression: str) -> None:
    parse_interval(expression)


def validate_task(task: Task) -> CalendarPreview | None:
    validate_task_id(task.task_id)
    if "\n" in (task.name or "") or "\r" in (task.name or ""):
        raise TaskError("display name must be a single line")
    if not task.working_directory.is_dir():
        raise TaskError(f"working directory does not exist: {task.working_directory}")
    if any(
        ord(character) < 32 or ord(character) == 127 for character in str(task.working_directory)
    ):
        raise TaskError("working directory contains control characters")
    if task.prompt_kind == "inline":
        if not task.prompt:
            raise TaskError("inline prompt must not be empty")
    else:
        prompt_path = Path(task.prompt)
        if not prompt_path.is_file():
            raise TaskError(f"prompt file does not exist: {prompt_path}")
    if task.thinking not in THINKING_LEVELS:
        raise TaskError(f"thinking must be one of: {', '.join(THINKING_LEVELS)}")
    if task.trust not in TRUST_POLICIES:
        raise TaskError(f"trust must be one of: {', '.join(TRUST_POLICIES)}")
    if task.schedule_kind == "interval" and task.catch_up:
        raise TaskError("interval schedules do not support calendar catch-up")
    validate_model(task.model)
    if task.schedule_kind == "calendar":
        return validate_calendar(task.schedule)
    validate_interval(task.schedule)
    return None


def has_saved_project_trust(working_directory: Path) -> bool:
    configured_agent_dir = os.environ.get("PI_CODING_AGENT_DIR")
    agent_dir = (
        Path(configured_agent_dir).expanduser()
        if configured_agent_dir
        else Path.home() / ".pi" / "agent"
    )
    trust_path = agent_dir / "trust.json"
    try:
        with trust_path.open() as stream:
            decisions = json.load(stream)
    except OSError, json.JSONDecodeError:
        return False
    if not isinstance(decisions, dict):
        return False

    current = working_directory.resolve()
    while True:
        decision = decisions.get(str(current))
        if isinstance(decision, bool):
            return True
        if current == current.parent:
            return False
        current = current.parent


def _toml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def serialize_task(task: Task) -> str:
    lines = [
        "version = 1",
        f"id = {_toml_string(task.task_id)}",
    ]
    if task.name is not None:
        lines.append(f"name = {_toml_string(task.name)}")
    lines.extend(
        [
            f"working_directory = {_toml_string(str(task.working_directory))}",
            f"model = {_toml_string(task.model)}",
            f"thinking = {_toml_string(task.thinking)}",
            f"timeout_seconds = {task.timeout_seconds}",
            f"trust = {_toml_string(task.trust)}",
            f"paused = {'true' if task.paused else 'false'}",
            f"result_reporting = {'true' if task.result_reporting else 'false'}",
            "",
            "[prompt]",
            f"{task.prompt_kind} = {_toml_string(task.prompt)}",
            "",
            "[schedule]",
        ]
    )
    if task.schedule_kind == "calendar":
        lines.extend(
            [
                'kind = "calendar"',
                f"expression = {_toml_string(task.schedule)}",
                f"catch_up = {'true' if task.catch_up else 'false'}",
            ]
        )
    else:
        lines.extend(
            [
                'kind = "interval"',
                f"every = {_toml_string(task.schedule)}",
            ]
        )
    lines.append("")
    return "\n".join(lines)


def _systemd_quote(value: str) -> str:
    escaped = value.replace("%", "%%").replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def runtime_max_seconds(timeout_seconds: int) -> int:
    """Hard systemd runtime limit: task timeout plus hung-wrapper grace."""
    return timeout_seconds + RUNTIME_BACKSTOP_GRACE_SECONDS


def service_unit(task: Task) -> str:
    executable = _resolve_executable("pi-task", "PI_TASK_EXECUTABLE")
    return (
        _GENERATED
        + f"""[Unit]
Description=Run pi-task {task.task_id}

[Service]
Type=oneshot
WorkingDirectory={task.working_directory!s}
ExecStart={_systemd_quote(executable)} _run-scheduled {task.task_id} --source scheduled
RuntimeMaxSec={runtime_max_seconds(task.timeout_seconds)}
TimeoutStopSec={TIMEOUT_STOP_SECONDS}
"""
    )


def timer_unit(task: Task) -> str:
    if task.schedule_kind == "calendar":
        schedule = (
            f"OnCalendar={task.schedule}\nPersistent={'true' if task.catch_up else 'false'}\n"
        )
    else:
        schedule = f"OnActiveSec={task.schedule}\nOnUnitActiveSec={task.schedule}\n"
    return (
        _GENERATED
        + f"""[Unit]
Description=Schedule pi-task {task.task_id}

[Timer]
{schedule}Unit=pi-task-{task.task_id}.service

[Install]
WantedBy=timers.target
"""
    )


def _write_staged(path: Path, content: str) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w") as stream:
            stream.write(content)
            stream.flush()
            os.fsync(stream.fileno())
    except BaseException:
        temporary.unlink(missing_ok=True)
        raise
    return temporary


def _systemctl(
    *arguments: str,
    allowed_statuses: tuple[int, ...] = (0,),
    timeout: float = 10,
) -> str:
    executable = _resolve_executable("systemctl", "PI_TASK_SYSTEMCTL_EXECUTABLE")
    result = _run([executable, "--user", *arguments], timeout=timeout)
    if result.returncode not in allowed_statuses:
        detail = result.stderr.strip() or f"systemctl exited with status {result.returncode}"
        raise TaskError(detail)
    return result.stdout.strip()


@dataclass(frozen=True)
class ManualRunSubmission:
    """Result of submitting a manual run through a transient systemd service."""

    run_id: str
    unit: str


def manual_unit_name(task_id: str, run_id: str) -> str:
    """Build a unique transient unit name for one manual run."""
    # systemd unit names accept the UUID hex form without hyphens.
    suffix = run_id.replace("-", "")
    return f"pi-task-run-{task_id}-{suffix}"


def scheduled_unit_name(task_id: str) -> str:
    """systemd unit name for a task's generated oneshot service."""
    return f"pi-task-{task_id}.service"


def unit_name_for_run(*, task_id: str, run_id: str, source: Literal["scheduled", "manual"]) -> str:
    """Resolve the systemd unit that supervises a recorded run."""
    if source == "scheduled":
        return scheduled_unit_name(task_id)
    return f"{manual_unit_name(task_id, run_id)}.service"


def supervising_unit(
    *,
    recorded_unit: str | None,
    task_id: str,
    run_id: str,
    source: Literal["scheduled", "manual"],
) -> str:
    """Prefer the unit stored on the run row; recompute for pre-v2 history."""
    if recorded_unit:
        return recorded_unit
    return unit_name_for_run(task_id=task_id, run_id=run_id, source=source)


def _systemd_run_detail(result: subprocess.CompletedProcess[str]) -> str | None:
    detail = result.stderr.strip() or result.stdout.strip()
    if detail:
        return detail
    if result.returncode != 0:
        return f"systemd-run exited with status {result.returncode}"
    return None


def start_manual_run(task_id: str) -> ManualRunSubmission:
    """Start a uniquely named transient user service that runs the task once.

    The recurring timer is never started, stopped, enabled, disabled, or restarted.
    The wrapper enforces the task timeout; this call returns after systemd accepts the
    transient service and does not wait for the Run to finish.
    """
    task = get_task(task_id)
    run_id = str(uuid.uuid4())
    unit = manual_unit_name(task.task_id, run_id)
    pi_task = _resolve_executable("pi-task", "PI_TASK_EXECUTABLE")
    systemd_run = _resolve_executable("systemd-run", "PI_TASK_SYSTEMD_RUN_EXECUTABLE")

    command = [
        systemd_run,
        "--user",
        "--no-block",
        f"--unit={unit}",
        "--collect",
        "--property=Type=oneshot",
        f"--property=RuntimeMaxSec={runtime_max_seconds(task.timeout_seconds)}",
        f"--property=TimeoutStopSec={TIMEOUT_STOP_SECONDS}",
        f"--description=Manual pi-task run {task.task_id}",
        f"--working-directory={task.working_directory}",
        pi_task,
        "_run-scheduled",
        task.task_id,
        "--source",
        "manual",
        "--run-id",
        run_id,
    ]

    try:
        result = subprocess.run(
            command,
            check=False,
            capture_output=True,
            text=True,
            env={**os.environ, "LC_ALL": "C"},
        )
    except OSError as error:
        raise TaskError(f"could not submit manual run: {error}") from error

    if result.returncode != 0:
        detail = _systemd_run_detail(result)
        raise TaskError(f"could not submit manual run: {detail}")
    return ManualRunSubmission(run_id=run_id, unit=unit)


def stop_user_unit(unit: str, *, timeout: float = SYSTEMCTL_STOP_TIMEOUT_SECONDS) -> None:
    """Stop a systemd user unit (used by cancel to terminate an active run)."""
    _systemctl("stop", unit, timeout=timeout)


def _task_paths(task_id: str) -> tuple[Path, Path, Path]:
    return (
        task_directory() / f"{task_id}.toml",
        unit_directory() / f"pi-task-{task_id}.service",
        unit_directory() / f"pi-task-{task_id}.timer",
    )


def _clear_timer_stamp(task_id: str) -> None:
    timer_stamp_path(task_id).unlink(missing_ok=True)


def _disable_timer(task_id: str) -> None:
    _systemctl(
        "disable",
        "--now",
        f"pi-task-{task_id}.timer",
        allowed_statuses=(0, 1, 5),
    )


def _enable_timer(task_id: str) -> None:
    _systemctl("enable", "--now", f"pi-task-{task_id}.timer")


def _install_task_files(task: Task) -> list[Path]:
    paths = _task_paths(task.task_id)
    contents = (serialize_task(task), service_unit(task), timer_unit(task))
    staged: list[Path] = []
    installed: list[Path] = []
    try:
        for path, content in zip(paths, contents, strict=True):
            staged.append(_write_staged(path, content))
        for temporary, destination in zip(staged, paths, strict=True):
            os.replace(temporary, destination)
            installed.append(destination)
    except BaseException:
        for temporary in staged:
            temporary.unlink(missing_ok=True)
        raise
    return installed


def create_task(task: Task) -> None:
    paths = _task_paths(task.task_id)
    if any(path.exists() for path in paths):
        raise TaskError(f"task {task.task_id!r} already exists")

    installed: list[Path] = []
    try:
        installed.extend(_install_task_files(task))
        _systemctl("daemon-reload")
        if not task.paused:
            _enable_timer(task.task_id)
    except BaseException:
        if not task.paused:
            with suppress(TaskError):
                _disable_timer(task.task_id)
        for path in installed:
            path.unlink(missing_ok=True)
        with suppress(TaskError):
            _systemctl("daemon-reload")
        raise


def _write_task_definition(task: Task) -> None:
    path = task_directory() / f"{task.task_id}.toml"
    temporary = _write_staged(path, serialize_task(task))
    try:
        os.replace(temporary, path)
    except BaseException:
        temporary.unlink(missing_ok=True)
        raise


def load_task(path: Path) -> Task:
    try:
        with path.open("rb") as stream:
            data = tomllib.load(stream)
        prompt = data["prompt"]
        schedule = data["schedule"]
        prompt_kinds = [kind for kind in ("inline", "file") if kind in prompt]
        if len(prompt_kinds) != 1:
            raise ValueError("unsupported task shape")
        kind = schedule["kind"]
        if kind == "calendar":
            schedule_value = schedule["expression"]
            catch_up = bool(schedule.get("catch_up", True))
        elif kind == "interval":
            schedule_value = schedule["every"]
            catch_up = False
        else:
            raise ValueError("unsupported task shape")
        result_reporting = data.get("result_reporting", False)
        if not isinstance(result_reporting, bool):
            raise ValueError("result_reporting must be a boolean")
        return Task(
            task_id=data["id"],
            name=data.get("name"),
            working_directory=Path(data["working_directory"]),
            prompt_kind=cast("Literal['inline', 'file']", prompt_kinds[0]),
            prompt=prompt[prompt_kinds[0]],
            schedule_kind=cast("Literal['calendar', 'interval']", kind),
            schedule=schedule_value,
            catch_up=catch_up,
            model=data["model"],
            thinking=data["thinking"],
            timeout_seconds=data["timeout_seconds"],
            trust=data["trust"],
            paused=data["paused"],
            result_reporting=result_reporting,
        )
    except (KeyError, OSError, TypeError, ValueError, tomllib.TOMLDecodeError) as error:
        raise TaskError(f"could not read task definition {path}: {error}") from error


def get_task(task_id: str) -> Task:
    validate_task_id(task_id)
    path = task_directory() / f"{task_id}.toml"
    if not path.is_file():
        raise TaskError(f"task {task_id!r} does not exist")
    return load_task(path)


def all_tasks() -> list[Task]:
    directory = task_directory()
    if not directory.is_dir():
        return []
    return [load_task(path) for path in sorted(directory.glob("*.toml"))]


def scheduling_state(task: Task) -> SchedulingState:
    unit = f"pi-task-{task.task_id}.timer"
    try:
        enabled = _systemctl("is-enabled", unit, allowed_statuses=(0, 1, 3, 4))
        active = _systemctl("is-active", unit, allowed_statuses=(0, 1, 3, 4))
    except TaskError:
        if task.paused:
            return SchedulingState(
                "paused (timer state unavailable)", "paused (timer state unavailable)"
            )
        return SchedulingState("unavailable", "unavailable")
    if task.paused:
        if enabled in {"disabled", "not-found", "masked", ""} and active != "active":
            return SchedulingState("paused", "paused")
        detail = f"paused (timer is {enabled or 'not enabled'}, {active or 'inactive'})"
        return SchedulingState(detail, detail)
    if enabled == "enabled":
        detail = f"enabled ({active or 'inactive'})"
        return SchedulingState(detail, detail)
    detail = f"{enabled or 'not enabled'} ({active or 'inactive'})"
    return SchedulingState(detail, detail)


def pause_task(task_id: str) -> Task:
    task = get_task(task_id)
    updated = task if task.paused else replace(task, paused=True)
    if not task.paused:
        _write_task_definition(updated)
    try:
        # Always reconcile: a prior crash can leave paused=true while the timer is live.
        _disable_timer(task.task_id)
        _clear_timer_stamp(task.task_id)
    except TaskError:
        if not task.paused:
            with suppress(OSError, TaskError):
                _write_task_definition(task)
        raise
    return updated


def resume_task(task_id: str) -> Task:
    task = get_task(task_id)
    updated = task if not task.paused else replace(task, paused=False)
    if task.paused:
        _write_task_definition(updated)
    try:
        # Always reconcile enablement. Only clear the stamp when leaving a pause so a
        # healthy running task does not lose calendar catch-up state.
        if task.paused:
            _clear_timer_stamp(task.task_id)
        _enable_timer(task.task_id)
    except TaskError:
        if task.paused:
            with suppress(OSError, TaskError):
                _write_task_definition(task)
                _disable_timer(task.task_id)
        raise
    return updated


def _read_timer_stamp(task_id: str) -> bytes | None:
    path = timer_stamp_path(task_id)
    try:
        return path.read_bytes()
    except OSError:
        return None


def _restore_timer_stamp(task_id: str, content: bytes | None) -> None:
    path = timer_stamp_path(task_id)
    if content is None:
        path.unlink(missing_ok=True)
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(content)


def update_task(previous: Task, updated: Task) -> None:
    if previous.task_id != updated.task_id:
        raise TaskError("task ID cannot be changed")
    paths = _task_paths(updated.task_id)
    originals = [path.read_text() if path.is_file() else None for path in paths]
    stamp_original = _read_timer_stamp(updated.task_id)
    stamp_mutated = False
    try:
        _install_task_files(updated)
        _systemctl("daemon-reload")
        if updated.paused:
            _disable_timer(updated.task_id)
            _clear_timer_stamp(updated.task_id)
            stamp_mutated = True
        elif previous.paused:
            _clear_timer_stamp(updated.task_id)
            stamp_mutated = True
            _enable_timer(updated.task_id)
        else:
            # Interval edits always restart so the next fire is one full interval away.
            # Calendar schedule changes need a timer restart; unrelated edits leave the
            # running timer and catch-up stamp alone after daemon-reload.
            interval_restart = (
                updated.schedule_kind == "interval" or previous.schedule_kind == "interval"
            )
            schedule_changed = (
                previous.schedule_kind != updated.schedule_kind
                or previous.schedule != updated.schedule
                or previous.catch_up != updated.catch_up
            )
            if interval_restart or schedule_changed:
                _disable_timer(updated.task_id)
                if (
                    interval_restart
                    or previous.schedule_kind != updated.schedule_kind
                    or previous.schedule != updated.schedule
                ):
                    _clear_timer_stamp(updated.task_id)
                    stamp_mutated = True
                _enable_timer(updated.task_id)
    except BaseException:
        for path, original in zip(paths, originals, strict=True):
            if original is None:
                path.unlink(missing_ok=True)
            else:
                path.write_text(original)
        if stamp_mutated:
            with suppress(OSError):
                _restore_timer_stamp(updated.task_id, stamp_original)
        with suppress(TaskError):
            _systemctl("daemon-reload")
        if not previous.paused:
            with suppress(TaskError):
                _enable_timer(previous.task_id)
        else:
            with suppress(TaskError):
                _disable_timer(previous.task_id)
        raise


def remove_task(task_id: str) -> None:
    task = get_task(task_id)
    with suppress(TaskError):
        _disable_timer(task.task_id)
    _clear_timer_stamp(task.task_id)
    for path in _task_paths(task.task_id):
        path.unlink(missing_ok=True)
    _systemctl("daemon-reload")


def _is_generated(path: Path) -> bool:
    try:
        with path.open() as stream:
            return stream.readline() == _GENERATED
    except OSError:
        return False


def _unit_task_id(path: Path) -> str | None:
    match = _UNIT_NAME.fullmatch(path.name)
    return match.group("task_id") if match else None


def sync_tasks() -> SyncResult:
    tasks = all_tasks()
    known_ids = {task.task_id for task in tasks}
    unit_dir = unit_directory()
    unit_dir.mkdir(parents=True, exist_ok=True)

    for task in tasks:
        _install_task_files(task)

    orphans_removed = 0
    for path in sorted(unit_dir.glob("pi-task-*")):
        if not path.is_file() or not _is_generated(path):
            continue
        task_id = _unit_task_id(path)
        if task_id is None or task_id in known_ids:
            continue
        if path.name.endswith(".timer"):
            with suppress(TaskError):
                _disable_timer(task_id)
            _clear_timer_stamp(task_id)
        path.unlink(missing_ok=True)
        orphans_removed += 1

    _systemctl("daemon-reload")
    for task in tasks:
        if task.paused:
            with suppress(TaskError):
                _disable_timer(task.task_id)
            _clear_timer_stamp(task.task_id)
        else:
            # Restart so live timers pick up rewritten OnCalendar/OnActiveSec values.
            # Keep the stamp so calendar catch-up survives reconciliation.
            with suppress(TaskError):
                _disable_timer(task.task_id)
            _enable_timer(task.task_id)
    return SyncResult(tasks=len(tasks), orphans_removed=orphans_removed)
