from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import tempfile
import tomllib
from contextlib import suppress
from dataclasses import dataclass
from datetime import datetime
from itertools import pairwise
from pathlib import Path
from typing import Literal, cast

from pi_task.doctor import manager_pi_check, systemd_environment_check

THINKING_LEVELS = ("off", "minimal", "low", "medium", "high", "xhigh", "max")
TRUST_POLICIES = ("inherit", "approve", "deny")
_TASK_ID = re.compile(r"^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$")
_DURATION = re.compile(r"^(\d+)(s|m|h)$")
_GENERATED = "# Generated by pi-task. Do not edit.\n"


class TaskError(Exception):
    pass


@dataclass(frozen=True)
class Task:
    task_id: str
    name: str | None
    working_directory: Path
    prompt_kind: Literal["inline", "file"]
    prompt: str
    calendar: str
    model: str
    thinking: str
    timeout_seconds: int
    trust: str
    paused: bool


@dataclass(frozen=True)
class CalendarPreview:
    occurrences: tuple[str, ...]


@dataclass(frozen=True)
class SchedulingState:
    summary: str
    detail: str


def _config_home() -> Path:
    value = os.environ.get("XDG_CONFIG_HOME")
    return Path(value).expanduser() if value else Path.home() / ".config"


def task_directory() -> Path:
    return _config_home() / "pi-task" / "tasks"


def unit_directory() -> Path:
    return _config_home() / "systemd" / "user"


def _resolve_executable(name: str, override: str) -> str:
    configured = os.environ.get(override)
    if configured:
        candidate = Path(configured).expanduser()
        if candidate.is_file() and os.access(candidate, os.X_OK):
            return str(candidate.absolute())
        raise TaskError(f"{override} does not identify an executable file")
    executable = shutil.which(name)
    if executable is None:
        raise TaskError(f"{name} was not found on PATH")
    return executable


def _run(
    command: list[str], *, environment: dict[str, str] | None = None
) -> subprocess.CompletedProcess[str]:
    try:
        return subprocess.run(
            command,
            check=False,
            capture_output=True,
            text=True,
            timeout=10,
            env={**(environment if environment is not None else os.environ), "LC_ALL": "C"},
        )
    except (OSError, subprocess.TimeoutExpired) as error:
        raise TaskError(f"could not run {command[0]}: {error}") from error


def validate_task_id(task_id: str) -> None:
    if len(task_id) > 63 or not _TASK_ID.fullmatch(task_id):
        raise TaskError(
            "task ID must be a lowercase slug (letters, numbers, and single hyphens; "
            "maximum 63 characters)"
        )


def parse_timeout(value: str) -> int:
    match = _DURATION.fullmatch(value)
    if match is None:
        raise TaskError("timeout must be a positive duration such as 30m, 2h, or 45s")
    amount = int(match.group(1))
    multiplier = {"s": 1, "m": 60, "h": 3600}[match.group(2)]
    seconds = amount * multiplier
    if seconds == 0:
        raise TaskError("timeout must be greater than zero")
    return seconds


def validate_model(model: str) -> None:
    if model.count("/") != 1 or any(character.isspace() for character in model):
        raise TaskError("model must use the explicit provider/model form")
    systemd_status, manager_environment = systemd_environment_check()
    if manager_environment is None:
        raise TaskError(
            f"could not inspect models in the systemd user manager: {systemd_status.detail}"
        )
    pi_status, executable, manager_environment = manager_pi_check(manager_environment)
    if executable is None or manager_environment is None:
        raise TaskError(f"could not inspect models in the systemd user manager: {pi_status.detail}")
    result = _run([executable, "--list-models"], environment=manager_environment)
    if result.returncode != 0:
        detail = result.stderr.strip() or f"Pi exited with status {result.returncode}"
        raise TaskError(f"could not list models in the systemd user manager: {detail}")
    available = {
        f"{columns[0]}/{columns[1]}"
        for line in result.stdout.splitlines()[1:]
        if len(columns := line.split()) >= 2
    }
    if model not in available:
        raise TaskError(f"model {model!r} is not available to the systemd user manager")


def _parse_occurrence(value: str) -> datetime | None:
    fields = value.strip().split(maxsplit=1)
    if len(fields) != 2:
        return None
    timestamp = fields[1]
    if timestamp.endswith(" UTC"):
        timestamp = timestamp[:-4] + "+00:00"
    try:
        return datetime.fromisoformat(timestamp)
    except ValueError:
        return None


def validate_calendar(expression: str) -> CalendarPreview:
    if not expression.strip() or "\n" in expression or "\r" in expression:
        raise TaskError("calendar schedule must be a single non-empty expression")
    executable = _resolve_executable("systemd-analyze", "PI_TASK_SYSTEMD_ANALYZE_EXECUTABLE")
    result = _run([executable, "calendar", "--iterations=3", expression])
    if result.returncode != 0:
        detail = result.stderr.strip() or f"systemd-analyze exited with status {result.returncode}"
        raise TaskError(f"invalid calendar schedule: {detail}")

    occurrence_lines: list[str] = []
    parsed: list[datetime] = []
    for line in result.stdout.splitlines():
        if "Next elapse:" in line or re.search(r"Iteration #\d+:", line):
            value = line.split(":", 1)[1].strip()
            occurrence_lines.append(value)
            occurrence = _parse_occurrence(value)
            if occurrence is not None:
                parsed.append(occurrence)
    if len(occurrence_lines) < 2:
        raise TaskError("calendar schedule does not have enough future occurrences")
    if len(parsed) >= 2 and any(
        (later - earlier).total_seconds() < 60 for earlier, later in pairwise(parsed)
    ):
        raise TaskError("calendar schedules must recur no faster than once per minute")
    return CalendarPreview(tuple(occurrence_lines))


def validate_task(task: Task) -> CalendarPreview:
    validate_task_id(task.task_id)
    if "\n" in (task.name or "") or "\r" in (task.name or ""):
        raise TaskError("display name must be a single line")
    if not task.working_directory.is_dir():
        raise TaskError(f"working directory does not exist: {task.working_directory}")
    if any(
        ord(character) < 32 or ord(character) == 127 for character in str(task.working_directory)
    ):
        raise TaskError("working directory contains control characters")
    if task.prompt_kind == "inline":
        if not task.prompt:
            raise TaskError("inline prompt must not be empty")
    else:
        prompt_path = Path(task.prompt)
        if not prompt_path.is_file():
            raise TaskError(f"prompt file does not exist: {prompt_path}")
    if task.thinking not in THINKING_LEVELS:
        raise TaskError(f"thinking must be one of: {', '.join(THINKING_LEVELS)}")
    if task.trust not in TRUST_POLICIES:
        raise TaskError(f"trust must be one of: {', '.join(TRUST_POLICIES)}")
    validate_model(task.model)
    return validate_calendar(task.calendar)


def has_saved_project_trust(working_directory: Path) -> bool:
    configured_agent_dir = os.environ.get("PI_CODING_AGENT_DIR")
    agent_dir = (
        Path(configured_agent_dir).expanduser()
        if configured_agent_dir
        else Path.home() / ".pi" / "agent"
    )
    trust_path = agent_dir / "trust.json"
    try:
        with trust_path.open() as stream:
            decisions = json.load(stream)
    except OSError, json.JSONDecodeError:
        return False
    if not isinstance(decisions, dict):
        return False

    current = working_directory.resolve()
    while True:
        decision = decisions.get(str(current))
        if isinstance(decision, bool):
            return True
        if current == current.parent:
            return False
        current = current.parent


def _toml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def serialize_task(task: Task) -> str:
    lines = [
        "version = 1",
        f"id = {_toml_string(task.task_id)}",
    ]
    if task.name is not None:
        lines.append(f"name = {_toml_string(task.name)}")
    lines.extend(
        [
            f"working_directory = {_toml_string(str(task.working_directory))}",
            f"model = {_toml_string(task.model)}",
            f"thinking = {_toml_string(task.thinking)}",
            f"timeout_seconds = {task.timeout_seconds}",
            f"trust = {_toml_string(task.trust)}",
            f"paused = {'true' if task.paused else 'false'}",
            "",
            "[prompt]",
            f"{task.prompt_kind} = {_toml_string(task.prompt)}",
            "",
            "[schedule]",
            'kind = "calendar"',
            f"expression = {_toml_string(task.calendar)}",
            "",
        ]
    )
    return "\n".join(lines)


def _systemd_quote(value: str) -> str:
    escaped = value.replace("%", "%%").replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def service_unit(task: Task) -> str:
    executable = _resolve_executable("pi-task", "PI_TASK_EXECUTABLE")
    return (
        _GENERATED
        + f"""[Unit]
Description=Run pi-task {task.task_id}

[Service]
Type=oneshot
WorkingDirectory={_systemd_quote(str(task.working_directory))}
ExecStart={_systemd_quote(executable)} _run-scheduled {task.task_id}
"""
    )


def timer_unit(task: Task) -> str:
    return (
        _GENERATED
        + f"""[Unit]
Description=Schedule pi-task {task.task_id}

[Timer]
OnCalendar={task.calendar}
Unit=pi-task-{task.task_id}.service

[Install]
WantedBy=timers.target
"""
    )


def _write_staged(path: Path, content: str) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w") as stream:
            stream.write(content)
            stream.flush()
            os.fsync(stream.fileno())
    except BaseException:
        temporary.unlink(missing_ok=True)
        raise
    return temporary


def _systemctl(*arguments: str, allowed_statuses: tuple[int, ...] = (0,)) -> str:
    executable = _resolve_executable("systemctl", "PI_TASK_SYSTEMCTL_EXECUTABLE")
    result = _run([executable, "--user", *arguments])
    if result.returncode not in allowed_statuses:
        detail = result.stderr.strip() or f"systemctl exited with status {result.returncode}"
        raise TaskError(detail)
    return result.stdout.strip()


def create_task(task: Task) -> None:
    task_path = task_directory() / f"{task.task_id}.toml"
    service_path = unit_directory() / f"pi-task-{task.task_id}.service"
    timer_path = unit_directory() / f"pi-task-{task.task_id}.timer"
    paths = (task_path, service_path, timer_path)
    if any(path.exists() for path in paths):
        raise TaskError(f"task {task.task_id!r} already exists")

    staged: list[Path] = []
    installed: list[Path] = []
    try:
        staged.append(_write_staged(task_path, serialize_task(task)))
        staged.append(_write_staged(service_path, service_unit(task)))
        staged.append(_write_staged(timer_path, timer_unit(task)))
        for temporary, destination in zip(staged, paths, strict=True):
            os.replace(temporary, destination)
            installed.append(destination)
        _systemctl("daemon-reload")
        if not task.paused:
            _systemctl("enable", "--now", f"pi-task-{task.task_id}.timer")
    except BaseException:
        if not task.paused:
            with suppress(TaskError):
                _systemctl("disable", "--now", f"pi-task-{task.task_id}.timer")
        for temporary in staged:
            temporary.unlink(missing_ok=True)
        for path in installed:
            path.unlink(missing_ok=True)
        with suppress(TaskError):
            _systemctl("daemon-reload")
        raise


def load_task(path: Path) -> Task:
    try:
        with path.open("rb") as stream:
            data = tomllib.load(stream)
        prompt = data["prompt"]
        schedule = data["schedule"]
        prompt_kinds = [kind for kind in ("inline", "file") if kind in prompt]
        if len(prompt_kinds) != 1 or schedule["kind"] != "calendar":
            raise ValueError("unsupported task shape")
        return Task(
            task_id=data["id"],
            name=data.get("name"),
            working_directory=Path(data["working_directory"]),
            prompt_kind=cast("Literal['inline', 'file']", prompt_kinds[0]),
            prompt=prompt[prompt_kinds[0]],
            calendar=schedule["expression"],
            model=data["model"],
            thinking=data["thinking"],
            timeout_seconds=data["timeout_seconds"],
            trust=data["trust"],
            paused=data["paused"],
        )
    except (KeyError, OSError, TypeError, ValueError, tomllib.TOMLDecodeError) as error:
        raise TaskError(f"could not read task definition {path}: {error}") from error


def get_task(task_id: str) -> Task:
    validate_task_id(task_id)
    path = task_directory() / f"{task_id}.toml"
    if not path.is_file():
        raise TaskError(f"task {task_id!r} does not exist")
    return load_task(path)


def all_tasks() -> list[Task]:
    directory = task_directory()
    if not directory.is_dir():
        return []
    return [load_task(path) for path in sorted(directory.glob("*.toml"))]


def scheduling_state(task: Task) -> SchedulingState:
    unit = f"pi-task-{task.task_id}.timer"
    try:
        enabled = _systemctl("is-enabled", unit, allowed_statuses=(0, 1, 3, 4))
        active = _systemctl("is-active", unit, allowed_statuses=(0, 1, 3, 4))
    except TaskError:
        if task.paused:
            return SchedulingState(
                "paused (timer state unavailable)", "paused (timer state unavailable)"
            )
        return SchedulingState("unavailable", "unavailable")
    if task.paused:
        if enabled in {"disabled", "not-found", "masked", ""} and active != "active":
            return SchedulingState("paused", "paused")
        detail = f"paused (timer is {enabled or 'not enabled'}, {active or 'inactive'})"
        return SchedulingState(detail, detail)
    if enabled == "enabled":
        detail = f"enabled ({active or 'inactive'})"
        return SchedulingState(detail, detail)
    detail = f"{enabled or 'not enabled'} ({active or 'inactive'})"
    return SchedulingState(detail, detail)
